### ISSUE TITLE
Consider using tagged version

### ISSUE THREAD

**Issue by jdziemidowicz** [flexiondotorg/oab-java6#1]
Hi,
please consider using tagged version of my Java packaging script:
- that way you can have repeatable builds (master branch changes, so the builds created at different times can be slightly different)
- from time to time I can break something in master, using tagged version will make your script work regardless of any breakage in master

You can either hardcode the tag you want to use (like v6.30-2) or use something like this to detect newest version:

```
TAG=`git tag -l 'v6.30-*'|tail -n1`
git checkout $TAG
```

**Comment by jdziemidowicz** [comment]
Sorry, wrong button clicked;)

**Comment by flexiondotorg** [comment]
Hi!

Thanks for your great packaging work, without which my script would not exist. I had already considered linking to a tag or revision. I've just committed a version which uses tags. I've also seen your 'oracle-java7' stuff and intend to integrate with that too in the future ;-)

Regards.
