### ISSUE TITLE
line 363 should use [[ ]] rather than [ ]

### ISSUE THREAD

**Issue by ctgswallow** [flexiondotorg/oab-java6#11]
Hi,

I think word splitting in line 363 causes this error:

[: too many arguments

I'm running VMware to the result of "imvirt" is "VMware ESX Server".

Because of the issue with line 363, the oab-java6.sh script skips the entire routine that creates GPG keys and signs the repository?  Replacing [ ] with [[ ]] fixes the problem as [[ ]] disables word splitting:

if [[ `imvirt` != "OpenVZ" ]]; then

**Comment by flexiondotorg** [comment]
Hi,

Thanks for the bug report and fix.

Regards, Martin.
