### ISSUE TITLE
Error during package build

### ISSUE THREAD

**Issue by Alcar32** [flexiondotorg/oab-java6#110]
[x] Building the packages   dpkg-buildpackage: set CFLAGS to default value: -$
dpkg-buildpackage: set CPPFLAGS to default value:
dpkg-buildpackage: set LDFLAGS to default value: -Wl,-Bsymbolic-functions
dpkg-buildpackage: set FFLAGS to default value: -g -O2
dpkg-buildpackage: set CXXFLAGS to default value: -g -O2
dpkg-buildpackage: source package oracle-java7
dpkg-buildpackage: source version 7.25-1~lucid1
dpkg-buildpackage: source changed by root root@localhost.localdomain
dpkg-buildpackage: host architecture amd64
dpkg-checkbuilddeps: Unmet build dependencies: debhelper (>= 8)
dpkg-buildpackage: warning: Build dependencies/conflicts unsatisfied; aborting.
dpkg-buildpackage: warning: (Use -d flag to override.)
^H^H10167's retcode: 3

**Comment by flexiondotorg** [comment]
Building Java 7 on Ubuntu Lucid is no longer supported as the upstream scripts now require `debhelper`>=8. In the 0.2.9 release the script will catch this error and exit.
