### ISSUE TITLE
Non-privileged mode

### ISSUE THREAD

**Issue by eyealike** [flexiondotorg/oab-java6#13]
How difficult would it be to add a non-privileged mode that doesn't require to be run as root?

I would love to build this using our continuous integration system which obviously runs as a normal user. Another reason is that I don't feel comfortable running scripts as root that interact with websites.

I see two possible methods: simply omit the commands that require root privileges or hardcode the sudo into them. With the latter method, I could then give sudo access to these specific commands to my continuous integration user via /etc/sudoers.

**Comment by mikkorantalainen** [comment]
Perhaps fakeroot could fix the issue?

**Comment by eyealike** [comment]
Unfortunately, no most of the commands that require root privileges can't
run inside fakeroot, e.g. apt-get install mkdir /usr/local/... etc.

On Fri, Mar 30, 2012 at 12:02 AM, Mikko Rantalainen <
reply@reply.github.com

> wrote:
> 
> Perhaps fakeroot could fix the issue?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/flexiondotorg/oab-java6/issues/13#issuecomment-4837376

## 

Hannes Schmidt
Software Engineer
Eyealike, Inc.
206 696 2316
hannes@eyealike.com

**Comment by eyealike** [comment]
Just to be clear, this issue was closed as "won't fix". My pull request, which adds the capability to run this script as a normal user with certain sudo privileges, was rejected without further explanation.

See https://github.com/eyealike/oab-java6
