### ISSUE TITLE
Also allow Linux Mint users to run script

### ISSUE THREAD

**Issue by csperle** [flexiondotorg/oab-java6#2]
Please add 'lisa' (and maybe more Mint codenames) to the list of the allowed versions (line 188), so that Linux Mint users can use your script, too. See here for Linux Mint  codenames (and which Ubuntu version they are based on): http://www.linuxmint.com/oldreleases.php

Thanks for the cool script.

Regards
Christoph

**Comment by flexiondotorg** [comment]
Hi,

Thanks for the feedback. Good idea. I'm just about to commit a new version of the script which should work with Linux Mint. Let me know how it goes.

Regards, Martin.
