### ISSUE TITLE
Error checking certificate for edelivery.oracle.com

### ISSUE THREAD

**Issue by robcrowell** [flexiondotorg/oab-java6#22]
Attempted to install on an alestic Ubuntu 11.10 EC2 box.  Here's the log:

Downloading common.sh
 [x] Installing Java build requirements success
 [x] Making build directories success
 [x] Removing clones of https://github.com/rraptorr/sun-java6 success
 [x] Cloning https://github.com/rraptorr/sun-java6 success
 [x] Checking out v6.31-2 success
 [x] Getting Java SE download pagesuccess
 [x] Getting current release download page success
 [x] Downloading jdk-6u31-linux-i586.bin : 81.34 MB failed
 [i] Showing the last 5 lines from the logfile (/mnt/oab-java6.sh.log)...
ERROR: cannot verify edelivery.oracle.com's certificate, issued by `/C=US/O=Akamai Technologies Inc/CN=Akamai Subordinate CA 3':
  Unable to locally verify the issuer's authority.
To connect to edelivery.oracle.com insecurely, use`--no-check-certificate'.
885's retcode: 5

This patch seems to work:

```
diff --git a/oab-java6.sh b/oab-java6.sh
index deefa55..bd8fb56 100755
--- a/oab-java6.sh
+++ b/oab-java6.sh
@@ -297,7 +297,7 @@ do
     COOKIES="oraclelicensejdk-${JAVA_VER}u${JAVA_UPD}-oth-JPR=accept-securebackup-cookie;gpw_e24=http://edelivery.oracle.com"

     ncecho " [x] Downloading ${JAVA_BIN} : ${DOWNLOAD_SIZE} "
-    wget --header="Cookie: ${COOKIES}" -c "${DOWNLOAD_URL}" -O /var/local/oab/pkg/${JAVA_BIN} >> "$log" 2>&1 &
+    wget --no-check-certificate --header="Cookie: ${COOKIES}" -c "${DOWNLOAD_URL}" -O /var/local/oab/pkg/${JAVA_BIN} >> "$log" 2>&1 &
     pid=$!;progress_loop $pid

     ncecho " [x] Symlinking ${JAVA_BIN} "
```

**Comment by sreejith000** [comment]
dear sir,
 my mobile not conact internet
