### ISSUE TITLE
Use of uninitialized value $avail

### ISSUE THREAD

**Issue by rwasielewski** [flexiondotorg/oab-java6#25]
Machine:
AMI: ubuntu/images/ebs/ubuntu-oneiric-11.10-i386-server-20120222 (ami-8d5069f9)

---

oab-java6.sh v0.1.9 - Create a local 'apt' repository for Ubuntu Java packages.
Copyright (c) Martin Wimpress, http://flexion.org. MIT License

By running this script to download Java you acknowledge that you have
read and accepted the terms of the Oracle end user license agreement.
- http://www.oracle.com/technetwork/java/javase/terms/license/

If you want to see what this is script is doing while it is running then execute
the following from another shell:

  tail -f /home/ubuntu/oab-java6.sh.log

Downloading common.sh
 [x] Removing ppa:flexiondotorg/java success
 [x] Installing Java build requirements success
 [x] Making build directories success
 [x] Removing clones of https://github.com/rraptorr/sun-java6 success
 [x] Cloning https://github.com/rraptorr/sun-java6 success
 [x] Checking out v6.31-2 success
 [x] Getting Java SE download pagesuccess
 [x] Getting current release download page success
 [x] Downloading jdk-6u31-linux-i586.bin : 81.34 MB success
 [x] Symlinking jdk-6u31-linux-i586.bin success
 [x] Downloading jdk-6u31-linux-x64.bin : 81.62 MB success
 [x] Symlinking jdk-6u31-linux-x64.bin success
 [x] Updating the changelog success
 [x] Building the packages success
 [x] Moving the packages success
 [x] Creating Packages.gz file success
 [x] Creating Release file success
Use of uninitialized value $avail in concatenation (.) or string at /usr/share/perl5/ImVirt/Utils/dmidecode/kernel.pm line 45.
Use of uninitialized value $avail in concatenation (.) or string at /usr/share/perl5/ImVirt/Utils/dmidecode/kernel.pm line 45.
Use of uninitialized value $avail in concatenation (.) or string at /usr/share/perl5/ImVirt/Utils/dmidecode/kernel.pm line 45.
Use of uninitialized value $avail in concatenation (.) or string at /usr/share/perl5/ImVirt/Utils/dmidecode/kernel.pm line 45.
Use of uninitialized value $avail in concatenation (.) or string at /usr/share/perl5/ImVirt/Utils/dmidecode/kernel.pm line 45.
Use of uninitialized value $avail in concatenation (.) or string at /usr/share/perl5/ImVirt/Utils/dmidecode/kernel.pm line 45.
 [x] Create GnuPG configuration success
 [x] Start generating entropy success
 [x] Creating signing key success
 [x] Stop generating entropy success
 [x] Signing the 'Release' file success
 [x] Exporting public key success
 [x] Adding public key success
 [x] Update package list success
All done!

**Comment by flexiondotorg** [comment]
Hi,

The output regarding `Use of uninitialized value $avail in concatenation` is not directly generated by my script, it appears to be generated by `imvirt` which in turn is using `dmidecode`. I can't fix this :-(

Regards, Martin.
