### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by ryannathans** [flexiondotorg/oab-java6#3]
ryannathans@GingerbreadKitchen:~$ sudo ./oab-java6.sh -k jre
oab-java6.sh v0.1.2 - Install Java 6u30 from locally built packages.
Copyright (c) 2012 Flexion.Org, http://flexion.org. MIT License

By running this script to download and/or install Java you acknowledge that 
you have read and accepted the terms of the Oracle end user license agreement.
- http://www.oracle.com/technetwork/java/javase/terms/license/

If you want to see what this is script is doing while it is running then execute
the following from another shell:

  tail -f /home/ryannathans/oab-java6.sh.log

./oab-java6.sh: line 189: check_root: command not found
./oab-java6.sh: line 190: check_sudo: command not found
./oab-java6.sh: line 191: check_ubuntu: command not found
./oab-java6.sh: line 192: lsb: command not found
Here we go...
./oab-java6.sh: line 233: ncecho: command not found
./oab-java6.sh: line 234: : No such file or directory
./oab-java6.sh: line 235: progress: command not found
./oab-java6.sh: line 238: ncecho: command not found
./oab-java6.sh: line 239: : No such file or directory
./oab-java6.sh: line 240: progress: command not found
./oab-java6.sh: line 244: ncecho: command not found
./oab-java6.sh: line 245: : No such file or directory
./oab-java6.sh: line 246: progress: command not found
./oab-java6.sh: line 249: ncecho: command not found
./oab-java6.sh: line 251: progress: command not found
./oab-java6.sh: line 254: ncecho: command not found
./oab-java6.sh: line 255: : No such file or directory
./oab-java6.sh: line 256: : No such file or directory
./oab-java6.sh: line 257: progress: command not found
./oab-java6.sh: line 263: ncecho: command not found
./oab-java6.sh: line 264: : No such file or directory
./oab-java6.sh: line 265: progress_loop: command not found
./oab-java6.sh: line 267: ncecho: command not found
./oab-java6.sh: line 268: : No such file or directory
./oab-java6.sh: line 269: progress_loop: command not found
./oab-java6.sh: line 263: ncecho: command not found
./oab-java6.sh: line 264: : No such file or directory
./oab-java6.sh: line 265: progress_loop: command not found
./oab-java6.sh: line 267: ncecho: command not found
./oab-java6.sh: line 268: : No such file or directory
./oab-java6.sh: line 269: progress_loop: command not found
./oab-java6.sh: line 273: cd: /var/local/oab/sun-java6-6.30/: No such file or directory
head: cannot open `debian/changelog' for reading: No such file or directory
./oab-java6.sh: line 283: ncecho: command not found
./oab-java6.sh: line 284: : No such file or directory
./oab-java6.sh: line 285: progress: command not found
./oab-java6.sh: line 288: ncecho: command not found
./oab-java6.sh: line 289: : No such file or directory
./oab-java6.sh: line 290: progress_can_fail: command not found
./oab-java6.sh: line 293: ncecho: command not found
./oab-java6.sh: line 294: : No such file or directory
./oab-java6.sh: line 296: progress: command not found
./oab-java6.sh: line 295: : No such file or directory
./oab-java6.sh: line 310: ncecho: command not found
./oab-java6.sh: line 311: : No such file or directory
./oab-java6.sh: line 312: : No such file or directory
./oab-java6.sh: line 313: progress: command not found
./oab-java6.sh: line 319: ncecho: command not found
./oab-java6.sh: line 320: : No such file or directory
./oab-java6.sh: line 321: : No such file or directory
./oab-java6.sh: line 322: progress: command not found
All done!

**Comment by ryannathans** [comment]
Odd, I deleted /tmp/common.sh and it started working.

**Comment by ryannathans** [comment]
Worked, cool!

**Comment by abridgett** [comment]
Hi Martin :-)

Just hit this myself, it's due to the wget of common.sh failing.

installing ca-certificates package fixes this (as would supplying --no-check-certificates)

**Comment by flexiondotorg** [comment]
Thanks Adrian, I'll put a proper fix in today. 

_Sent via Hubroid_
