### ISSUE TITLE
404 in http://github.com/rraptorr/sun-java6/info/refs

### ISSUE THREAD

**Issue by madang** [flexiondotorg/oab-java6#32]
Well the whole http://github.com/rraptorr/sun-java6/info is actually missing
so the oab-java6.sh does not work.
here's the ouput

oab-java.sh v0.2.3 - Create a local 'apt' repository for Sun Java 6 and/or Oracle Java 7 packages.

Copyright (c) Martin Wimpress, http://flexion.org. MIT License

By running this script to download Java you acknowledge that you have
read and accepted the terms of the Oracle end user license agreement.
- http://www.oracle.com/technetwork/java/javase/terms/license/

If you want to see what this is script is doing while it is running then execute
the following from another shell:

  tail -f /home/h205g/oab-java6/oab-java.sh.log

 [x] Installing Java build requirements success
 [x] Making build directories success
 [x] Removing clones of http://github.com/rraptorr/sun-java6 success
 [x] Cloning http://github.com/rraptorr/sun-java6 failed
 [i] Showing the last 5 lines from the logfile (/home/h205g/oab-java6/oab-java.sh.log)...
error: Failed to connect to 207.97.227.239: Network is unreachable while accessing http://github.com/rraptorr/sun-java6/info/refs

fatal: HTTP request failed
13035's retcode: 128
failed

**Comment by flexiondotorg** [comment]
It works for me?

**Comment by madang** [comment]
Just checked again - does not work still 404. The protocol for some reason changes to https automatically though. Must be a github's feature.
