### ISSUE TITLE
Script can't find jdk-6u32-linux-i586.bin download file

### ISSUE THREAD

**Issue by lzhang** [flexiondotorg/oab-java6#33]
I am running the script on Ubuntu 12.04 LTS, though I suspect it would happen on any other version.

A failure occurs when attempting to retrieve the download for `jdk-6u32-linux-i586.bin`:

```
$ ./oab-java.sh 
oab-java.sh v0.2.3 - Create a local 'apt' repository for Sun Java 6 and/or Oracle Java 7 packages.

Copyright (c) Martin Wimpress, http://flexion.org. MIT License

By running this script to download Java you acknowledge that you have
read and accepted the terms of the Oracle end user license agreement.

* http://www.oracle.com/technetwork/java/javase/terms/license/

If you want to see what this is script is doing while it is running then execute
the following from another shell:

  tail -f /usr/local/src/oab-java6/oab-java.sh.log

 [x] Installing Java build requirements success
 [x] Making build directories success
 [x] Removing clones of http://github.com/rraptorr/sun-java6 success
 [x] Cloning http://github.com/rraptorr/sun-java6 success
 [x] Checking out v6.32-2 success
 [x] Getting Java SE download page success
 [x] Getting previous releases download page success
 [x] Downloading jdk-6u32-linux-i586.bin :  failed
 [i] Showing the last 5 lines from the logfile (/usr/local/src/oab-java6/oab-java.sh.log)...
16958's retcode: 0
success
 [x] Downloading jdk-6u32-linux-i586.bin :    http://: Invalid host name.
16976's retcode: 1
failed
```

This is because http://www.oracle.com/technetwork/java/javasebusiness/downloads/java-archive-downloads-javase6-419409.html no longer has any mention of `jdk-6u32-linux-i586.bin` for some reason.

I'm not sure what the appropriate resolution would be. Any thoughts?

**Comment by ajorgensen** [comment]
So it looks like the jdk-6u32-linux-i586.bin is located at http://www.oracle.com/technetwork/java/javase/downloads/jdk-6u32-downloads-1594644.html instead. For whatever reason they moved it.

Anyway i was able to change the URL at line number 447 so it looks like:

 wget http://www.oracle.com/technetwork/java/javase/downloads/jdk-6u32-downloads-1594644.html -O /tmp/oab-download.html >> "$log" 2>&1 &

Temporary fix i guess until a more elegant solution can be made.

**Comment by lzhang** [comment]
Yeah, I was able to arrive at the same solution. Looking at the way the script is structured though, it's not a longterm fix. Oracle :P

**Comment by racoonlab** [comment]
Yep same problem...thanks for your help

**Comment by racoonlab** [comment]
Well I have a problem with jdk-6u33-linux-i586.bin then I changed the line 447 to
ncecho " [x] Getting previous releases download page "
    if [ "${JAVA_UPSTREAM}" == "sun-java6" ]; then
       wget http://www.oracle.com/technetwork/java/javase/downloads/jdk6-downloads-1637591.html -O /tmp/oab-download.html >> "$log" 2>&1 &
    else

at this point it works a bit and then it fails in:
...
 [x] Symlinking jdk-6u33-linux-x64.bin success
 [x] Updating the changelog success
 [x] Building the packages success
ERROR! Packages failed to build.

and the logs say:

: # fix permissions
find x64-jdk -name '_.properties' -o -name '_.xml' | xargs chmod 644
touch unpack-x64-stamp
rm -rf jce
unzip -q jce_policy-6.zip
unzip:  cannot find or open jce_policy-6.zip, jce_policy-6.zip.zip or jce_policy-6.zip.ZIP.
make: **\* [unpack-jce-stamp] Error 9
dpkg-buildpackage: error: debian/rules build gave error exit status 2
^H^H13297's retcode: 2
success

Any other suggestion?

**Comment by jdziemidowicz** [comment]
The problem you are facing is caused by issue #31 To manually fix it, you have to download jce_policy-6.zip file located on Java download site (at the bottom).

**Comment by racoonlab** [comment]
Hi rraptor,

And now the trivial question...I downloaded it and place both into tmp and where my script is, but it doesn't work. I believe it is the wrong dir(?)

**Comment by jdziemidowicz** [comment]
I am sorry, but I do not maintain or use oab-java6, so I have no idea. I've created Debian packages that oab-java6 uses and I've made the changes that require this file. I've reported this a month ago to oab-java6 developer, but there was no response.
I can only guess you should put it in the same directory as the jdk .bin files.

**Comment by racoonlab** [comment]
Hi rraptorr,

Thank you for your help.

r

**Comment by jamesonjlee** [comment]
I'm writing a fix to handle this right now in my fork, it will/is also handling #31 as well.

**Comment by racoonlab** [comment]
Hi jamesonjlee,

Thanks for your help.
