### ISSUE TITLE
fails to create java7 local repository

### ISSUE THREAD

**Issue by sbrattla** [flexiondotorg/oab-java6#34]
Hi,

First of all; thanks for a great way to install java6 on Ubuntu. It works like a charm.

I've tried to install java7, but somehow it fails on my machine. Here's the command line output:

  tail -f /tmp/oab/oab-java.sh.log

 [x] Installing Java build requirements success
 [x] Making build directories success
 [x] Removing clones of http://github.com/rraptorr/oracle-java7 success
 [x] Cloning http://github.com/rraptorr/oracle-java7 success
 [x] Checking out v7.5-1 success
 [x] Getting Java SE download page success
 [x] Getting previous releases download page success
 [x] Downloading jdk-7u5-linux-i586.tar.gz :  failed
 [i] Showing the last 5 lines from the logfile (/tmp/oab/oab-java.sh.log)...
3091's retcode: 0
success
 [x] Downloading jdk-7u5-linux-i586.tar.gz :    http://: Invalid host name.
3108's retcode: 1
failed

Any idea what the cause might be?

**Comment by jamesonjlee** [comment]
this is because oracle moved the java download page see #33
