### ISSUE TITLE
provide script for manual downloads?

### ISSUE THREAD

**Issue by toddobryan** [flexiondotorg/oab-java6#35]
Since Oracle just moved the download page (and probably will in the future), would you consider providing a script that expects the user to download the two (or four) bin files and the jce files manually and then does all the magic with those files?

That way Oracle can't say that you're going around the license agreement.

**Comment by flexiondotorg** [comment]
Hi,

An updated version of the script will be released later today which fixes the download links. I intend to keep this `oab-java.sh` automated because if you require a manual solution then you can use Janusz Dziemidowicz packaging tools directly.
- https://github.com/rraptorr

Regards, Martin.
