### ISSUE TITLE
Packages failed to build

### ISSUE THREAD

**Issue by zgorbe** [flexiondotorg/oab-java6#39]
I got the following error when executing the oab-java.sh script (on Ubuntu 10.04 64 bit):
...
...
 [x] Symlinking jdk-6u33-linux-i586.bin success
 [x] Downloading jdk-6u33-linux-x64.bin :  success
 [x] Symlinking jdk-6u33-linux-x64.bin success
 [x] Updating the changelog success
 [x] Building the packages success
ERROR! Packages failed to build.

The end of the log file looks like this:
# Build information

TOP         = usr/lib/jvm
VENDOR      = sun
RELEASE     = 6
PRODUCT     = java6
basename    = sun-java6
version     = 6
releng_ver  = 33
unpackdir   = jdk1.6.0_33
srcdir      = x64-jdk
all_archs   = i586 x64
arch        = x64
archdir     = amd64
bin_pattern = jdk-6u33-linux-%.bin

rm -rf jdk1.6.0_33
binsize=$(wc -c jdk-6u33-linux-i586.bin | awk '{print $1}'); \
        zipstart=$(unzip -ql jdk-6u33-linux-i586.bin 2>&1 >/dev/null | sed -n -e 's/.\* ([0-9][0-9]_) extra bytes._/\1/p'); \
        tail -c $(expr $binsize - $zipstart) jdk-6u33-linux-i586.bin > tmp-jdk.zip
expr: syntax error
tail: jdk-6u33-linux-i586.bin: invalid number of bytes
make: **\* [unpack-i586-stamp] Error 1
dpkg-buildpackage: error: debian/rules build gave error exit status 2
^H^H1774's retcode: 2
success

Could you help me please to find out the root cause of this problem?

**Comment by jamesonjlee** [comment]
this is due to oracle changing links around and sun-java needing the JCE, see the pull-requests for a working fix (until flexiondotorg fixes them). see #37, #38
