### ISSUE TITLE
How to force install a specific version?

### ISSUE THREAD

**Issue by kripz** [flexiondotorg/oab-java6#40]
Can i specify or modify it to install 6u31 (for example)?

**Comment by kripz** [comment]
Can i change

JAVA_VER=`echo ${DEB_VERSION} | cut -d'.' -f1`
JAVA_UPD=`echo ${DEB_VERSION} | cut -d'.' -f2 | cut -d'-' -f1`

to

JAVA_VER=6
JAVA_UPD=31

**Comment by flexiondotorg** [comment]
Hi,

This is a good idea. You can hard code as kripz did above, but it should be implemented as an argument. Something like

./oab-java.sh -c 

Which will list the tags available upstream.

./oab-java.sh -c v6.31 

To specify a particular tag to use from upstream.

I don't have the time to add this feature right now, but might do in the future. If anyone cares to contribute a pull request though it would be most welcome :-)

Regards, Martin.

**Comment by kripz** [comment]
My OP didn't work, it's much more complicated than that.

**Comment by ConsoleCatzirl** [comment]
I hacked up a simple tag option, but I haven't added a way to list available tags.  Also, I can't figure out how to tell github to attached the code to this issue, so I'm going to open a new pull request.
