### ISSUE TITLE
Error downloading jce_policy-6.zip

### ISSUE THREAD

**Issue by GothAck** [flexiondotorg/oab-java6#41]
Trying to run the script as `sudo ./oab-java.sh`

Everything works until it tries to download the jce policy where it seems to fail to get a valid hostname:

`
 [x] Downloading jce_policy-6.zip : 8.89 KB   --2012-06-26 16:16:26--  http://java%20cryptography%20extension%20(jce)%20unlimited%20strength%20jurisdiction%20policy%20files%206jce_policy-6.zip/
Resolving java cryptography extension (jce) unlimited strength jurisdiction policy files 6jce_policy-6.zip (java cryptography extension (jce) unlimited strength jurisdiction policy files 6jce_policy-6.zip)... failed: Name or service not known.
wget: unable to resolve host address`java cryptography extension (jce) unlimited strength jurisdiction policy files 6jce_policy-6.zip'
31219's retcode: 4
`

**Comment by GothAck** [comment]
It seems https://github.com/flexiondotorg/oab-java6/blob/master/oab-java.sh#L487 needs the first `cut` changed to `-f9`

**Comment by flexiondotorg** [comment]
I've just retested and everything is working fine without the need for any code changes.

**Comment by reedstrm** [comment]
Seems Oracle's been messing the packages around again: I get:
 [x] Downloading jce_policy-6.zip :    --2013-07-21 13:28:12--  http://jce_policy-6.zip/
Resolving jce_policy-6.zip (jce_policy-6.zip)... failed: Name or service not known.
wget: unable to resolve host address `jce_policy-6.zip'
16946's retcode: 4
failed

Clearly failing to parse out the hostname for the url.

**Comment by fletchowns** [comment]
I'm also having the same issue that reedstrm ran into.

**Comment by alfetopito** [comment]
Same here
