### ISSUE TITLE
current download page has moved

### ISSUE THREAD

**Issue by orac** [flexiondotorg/oab-java6#44]
I tried to run this script and it failed in this manner:

```
 [x] Making build directories success
 [x] Removing clones of https://github.com/rraptorr/sun-java6 success
 [x] Cloning https://github.com/rraptorr/sun-java6 success
 [x] Checking out v6.33-1 success
 [x] Getting Java SE download pagesuccess
 [x] Getting previous releases download page success
 [x] Downloading jdk-6u33-linux-i586.bin :  failed
 [i] Showing the last 5 lines from the logfile (/home/danhul01/oab-java6.sh.log)...
12395's retcode: 0
success
 [x] Downloading jdk-6u33-linux-i586.bin :    http://: Invalid host name.
12414's retcode: 1
failed
```

Debugging a little, I saw that in /tmp/oab-index.html, there wasn't a link of the form `jdk-6u33-downloads-\d+`, which is what the script searches for on line 278. In the current index page, the correct link has the form `jdk6-downloads-\d+`. That's incredibly useless, I know, because it's not specific to the update number, so it doesn't tell you whether to use the 'current' or 'previous' releases pages. A real change to fix this will probably involve downloading and grepping both the current and previous pages to find the package URL, but I hacked it to work for me by replacing line 278 with

```
DOWNLOAD_INDEX=`grep -P -o "/technetwork/java/javase/downloads/jdk${JAVA_VER}-downloads-\d+\.html" /tmp/oab-index.html | uniq`
```

**Comment by ExPeacer** [comment]
Thanks a lot! This is exactly what I need :)

**Comment by realgt** [comment]
Worked for me, downloaded 6u33. thx @orac

**Comment by jpanganiban** [comment]
Great! Thanks for the quick fix!

**Comment by flexiondotorg** [comment]
I've just retested everything and it worked fine without the need for any code changes.

**Comment by orac** [comment]
A colleague tried it recently and said the same thing. Whatever change they made, they must have changed it back. OAB, I guess!
