### ISSUE TITLE
Build Packages Fails - Java 6

### ISSUE THREAD

**Issue by Xitesmai** [flexiondotorg/oab-java6#45]
I tried to execute the script...and the packages failed to build.

Not sure whats going on, because it worked this morning.

```
 [x] Installing Java build requirementssuccess
 [x] Making build directoriessuccess
 [x] Removing clones of https://github.com/rraptorr/sun-java6success
 [x] Cloning https://github.com/rraptorr/sun-java6success
 [x] Checking out v6.33-1success
 [x] Getting Java SE download pagesuccess
 [x] Getting current release download pagesuccess
 [x] Downloading jdk-6u33-linux-i586.bin : 68.42 MBsuccess
 [x] Symlinking jdk-6u33-linux-i586.binsuccess
 [x] Downloading jdk-6u33-linux-x64.bin : 68.69 MBsuccess
 [x] Symlinking jdk-6u33-linux-x64.binsuccess
 [x] Getting Java Cryptography Extension download pagesuccess
 [x] Downloading jce_policy-6.zip : 8.89 KBsuccess
 [x] Symlinking jce_policy-6.zipsuccess
 [x] Updating the changelogsuccess
 [x] Building the packagessuccess
ERROR! Packages failed to build.
```

I checked the log and this was the last entry

```
make: *** [unpack-stamp] Error 1
dpkg-buildpackage: error: debian/rules build gave error exit status 2
9656's retcode: 2
success
```

**Comment by jstew7** [comment]
I'm having same issue, got same result with '-7' param as well.

**Comment by mickgleeson** [comment]
yep, same problem - any update on this? 

Thanks

**Comment by Fruff** [comment]
Me too, both packages.

logfile after trying -7:

make: **\* [unpack-stamp] Error 1
dpkg-buildpackage: error: debian/rules build gave error exit status 2
19492's retcode: 2
success

**Comment by bwhite** [comment]
Same here

**Comment by araddon** [comment]
A temporary fix is to comment out this line:  

https://github.com/flexiondotorg/oab-java6/blob/master/oab-java.sh#L421

That line checks out the last tagged version of https://github.com/rraptorr/sun-java6 which does not include this (necessary) fix https://github.com/rraptorr/sun-java6/commit/c8624657c61d54d7a0788d37c26f388a5d0c31b5

**Comment by tnj** [comment]
I tried @araddon's fix and it worked fine. Thanks.

**Comment by nifgraup** [comment]
@araddon thanks, works for me too.

**Comment by araddon** [comment]
This issue should be able to be closed now with this fix:  https://github.com/rraptorr/sun-java6/issues/16

**Comment by flexiondotorg** [comment]
@araddon - Many thanks for the clarification on this issue. I've justed retested and all is well :-)
