### ISSUE TITLE
Couldn't resolve host 'github.com' while accessing https://github.com/rraptorr/sun-java6/info/refs

### ISSUE THREAD

**Issue by frankscholten** [flexiondotorg/oab-java6#48]
I get the following error when I run

$ sudo ./oab-java.sh

 [x] Installing Java build requirements success
 [x] Making build directories success
 [x] Removing clones of https://github.com/rraptorr/sun-java6 success
 [x] Cloning https://github.com/rraptorr/sun-java6 failed
 [i] Showing the last 5 lines from the logfile (/home/vagrant/oab-java.sh.log)...
error: Couldn't resolve host 'github.com' while accessing https://github.com/rraptorr/sun-java6/info/refs

The same kind of error occurs when I run

$ sudo oab-java.sh -7

**Comment by flexiondotorg** [comment]
This is not something I can fix in the script. Looks like a DNS or issue?

**Comment by bsateeshk** [comment]
Hi Flex,
would you please suggest how the issue got closed?  I am facing similar issue and i need to fix it.. Kindly suggest.
