### ISSUE TITLE
invalid hostname  jdk-6u33-linux-i586.bin

### ISSUE THREAD

**Issue by ericjang** [flexiondotorg/oab-java6#51]
tail -f /home/NEF/Downloads/oab-java6.sh.log

 [x] Installing Java build requirementssuccess
 [x] Making build directoriessuccess
 [x] Removing clones of http://github.com/rraptorr/sun-java6success
 [x] Cloning http://github.com/rraptorr/sun-java6success
 [x] Checking out v6.33-2success
 [x] Getting Java SE download pagesuccess
 [x] Getting current release download pagesuccess
 [x] Getting previous releases download pagesuccess
 [x] Downloading jdk-6u33-linux-i586.bin : failed
 [i] Showing the last 5 lines from the logfile (/home/NEF/Downloads/oab-java6.sh.log)...
10395's retcode: 0
success
 [x] Downloading jdk-6u33-linux-i586.bin :   http://: Invalid host name.
10412's retcode: 1
failed

**Comment by stealthiscode** [comment]
I'm seeing the same thing, while trying to install Java 6.  I installed Java 7 three days ago, without any issues.

**Comment by bueti** [comment]
same here. tricked it with hardcoding to u32, but then the build fails.

**Comment by miniworm** [comment]
6u33 and 7u5 are deprecated by Oracle and unavailable on their servers. Take a look at issue 52 and temporary solutions for it.

**Comment by flexiondotorg** [comment]
Hi,

This could be mitigated by improving the error handling in the script, sadly something I don't have time to add at the moment. Pull requests welcomed :-)

Regards, Martin.

**Comment by sarmbruster** [comment]
same here for 6u35 (which contains some important security fix)

**Comment by miniworm** [comment]
URL for java 6u35  (change in line 451):

http://www.oracle.com/technetwork/java/javase/downloads/jdk6u35-downloads-1836443.html

URL for java 7u7  (change in line 453):

http://www.oracle.com/technetwork/java/javase/downloads/jdk7u7-downloads-1836413.html

It's the only change needed from original script to make it work this time.

**Comment by thearc77** [comment]
Thank miniworm!!!

**Comment by miniworm** [comment]
I've discovered that in fact the only change needed (maybe also for future updates) is in line 443. Now it looks like this:

DOWNLOAD_INDEX=`grep -P -o "/technetwork/java/javase/downloads/jdk${JAVA_VER}-downloads-\d+\.html" /tmp/oab-index.html | uniq`

And should be:

DOWNLOAD_INDEX=`grep -P -o "/technetwork/java/javase/downloads/jdk${JAVA_VER}u${JAVA_UPD}-downloads-\d+\.html" /tmp/oab-index.html | uniq`

So adding u${JAVA_UPD} makes everything OK (I think it's change in HTML structure on Oracle webpage)

**Comment by jefft** [comment]
Thanks miniworm, your solution is correct, but markdown ate your backticks. Line 443 should go from:

``` shell
DOWNLOAD_INDEX=`grep -P -o "/technetwork/java/javase/downloads/jdk${JAVA_VER}-downloads-\d+\.html" /tmp/oab-index.html | uniq`
```

to:

``` shell
DOWNLOAD_INDEX=`grep -P -o "/technetwork/java/javase/downloads/jdk${JAVA_VER}u${JAVA_UPD}-downloads-\d+\.html" /tmp/oab-index.html | uniq`
```

**Comment by di** [comment]
Thanks @miniworm and @jefft !!!

**Comment by flexiondotorg** [comment]
Fixed in 0.2.6

**Comment by manojiitkgp09** [comment]
Thanks! Saved my day :)

**Comment by ElijahLynn** [comment]
Happening to me in 0.2.6 on Ubuntu 12.04

Update: Only difference is "Downloading jdk-6u35-linux-i586.bin" vs 6u33

**Comment by ElijahLynn** [comment]
Should I make a new thread or just use this one? It is the same thing.
