### ISSUE TITLE
both 6u33 and 7u5 are deprecated by Oracle

### ISSUE THREAD

**Issue by pkit** [flexiondotorg/oab-java6#52]
Your script is unusable now because these releases do not exist on Oracle servers anymore

**Comment by miniworm** [comment]
Temporary solution for java6 (but working - similar for java7):

Change:

DEB_VERSION=`head -n1 ${WORK_PATH}/src/debian/changelog | cut -d'(' -f2 | cut -d')' -f1 | cut -d'~' -f1`

to

DEB_VERSION=6.34-1

---

JAVA_VER=echo ${DEB_VERSION} | cut -d'.' -f1
JAVA_UPD=echo ${DEB_VERSION} | cut -d'.' -f2 | cut -d'-' -f1

to

JAVA_VER=6
JAVA_UPD=34

---

wget http://www.oracle.com/technetwork/java/javasebusiness/downloads/java-archive-downloads-javase6-419409.html -O /tmp/oab-download.html >> "$log" 2>&1 &

to

wget http://www.oracle.com/technetwork/java/javase/downloads/jdk6-downloads-1637591.html -O /tmp/oab-download.html >> "$log" 2>&1 &

**Comment by miniworm** [comment]
Temporary solution for java7:

Change:

DEB_VERSION=head -n1 ${WORK_PATH}/src/debian/changelog | cut -d'(' -f2 | cut -d')' -f1 | cut -d'~' -f1

to

DEB_VERSION=7.6-1

---

JAVA_VER=echo ${DEB_VERSION} | cut -d'.' -f1
JAVA_UPD=echo ${DEB_VERSION} | cut -d'.' -f2 | cut -d'-' -f1

to

JAVA_VER=7
JAVA_UPD=6

_________________________________________________________________________________________-

wget http://www.oracle.com/technetwork/java/javasebusiness/downloads/java-archive-downloads-javase7-521261.html -O /tmp/oab-download.html >> "$log" 2>&1 &

to

wget http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1637583.html -O /tmp/oab-download.html >> "$log" 2>&1 &

**Comment by mark541** [comment]
After making the changes for version 7, I still have errors, see below;
debian/control did change, please restart the build
make: **\* [debian/control] Error 1
dpkg-buildpackage: error: debian/rules build gave error exit status 2
18151's retcode: 2
success

I get essentially the same error if I change it for version 6 and rerun.

**Comment by sT4k3** [comment]
I got the same error for java se 6u34 on my Ubuntu 10.04 i686 :(

```
          -e 's/@JDK@/sun-java6-jdk/g' \
          -e 's/@vendor@/Sun/g' \
          -e 's/@basename@/sun-java6/g' \
          -e 's,@basedir@,usr/lib/jvm/java-6-sun-1.6.0.34,g' \
          -e 's/@arch@/i386/g' \
          -e 's/@RELEASE@/6/g' \
          -e 's/@archdir@/i386/g' \
          -e 's/@browsers@/firefox | firefox-2 | iceweasel | mozilla-firefox | iceape-browser | mozilla-browser | epiphany-gecko | epiphany-webkit | epiphany-browser | galeon | midbrowser | konqueror | chromium-browser | midori | google-chrome/g' \
          -e 's/@cjk_fonts@/ttf-baekmuk | ttf-unfonts-core, ttf-kochi-gothic | ttf-sazanami-gothic, ttf-kochi-mincho | ttf-sazanami-mincho, ttf-arphic-uming,/g' \
          -e 's/@jdkversion@/1.6.0/g' \
          -e 's/@releng_ver@/34/g' \
        debian/control.in > debian/control
```

debian/control did change, please restart the build
make: **\* [debian/control] Ошибка 1
dpkg-buildpackage: ошибка: debian/rules build возвратил код ошибки 2

**Comment by miniworm** [comment]
Sorry - I've tested only on Ubuntu 12.04.

BTW - if you make changes for version 7 do you run oab-java.sh with "-7" switch to actually make use of it?

**Comment by mark541** [comment]
I'm running Xubuntu 12.04, and yes, I used the "-7" switch. The whole command string used was;
sudo ./oab-java.sh -7

**Comment by miniworm** [comment]
I know that maybe it's totally unusable for you but I've downloaded latest oab-java.sh, applied my changes, run it and everything went 100% OK for both versions (6&7). So don't know what went wrong fo you. Could you provide more info from log file?

**Comment by pkit** [comment]
It was 404 here couple of hours ago:

http://www.oracle.com/technetwork/java/javasebusiness/downloads/java-archive-downloads-javase7-521261.html

Now it looks like this:

 [x] Getting Java SE download page   --2012-08-16 01:06:04--  http://www.oracle.com/technetwork/java/javase/downloads/index.html
Resolving www.oracle.com (www.oracle.com)... 23.34.225.55
Connecting to www.oracle.com (www.oracle.com)|23.34.225.55|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: `/tmp/oab-index.html'

```
 0K .......... .......... .......... .......... ..........  408K
50K .......... .......... .......... .......... ..........  625K
```

   100K .......... .......... .......... .......... .........   797K=0.3s

2012-08-16 01:06:04 (565 KB/s) - `/tmp/oab-index.html' saved [153598]

13697's retcode: 0
success
 [x] Getting current release download page   --2012-08-16 01:06:04--  http://www.oracle.com//technetwork/java/javase/downloads/jdk7-downloads-1637583.html
Resolving www.oracle.com (www.oracle.com)... 23.34.225.55
Connecting to www.oracle.com (www.oracle.com)|23.34.225.55|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: `/tmp/oab-download.html'

```
 0K .......... .......... .......... .......... ..........  382K
50K .......... .......... .......... .......... ..........  508K
```

   100K .......... .......... .......... .......... ........    749K=0.3s

2012-08-16 01:06:05 (505 KB/s) - `/tmp/oab-download.html' saved [151822]

13707's retcode: 0
success
 [x] Getting previous releases download page   --2012-08-16 01:06:05--  http://www.oracle.com/technetwork/java/javasebusiness/downloads/java-archive-downloads-javase7-521261.html
Resolving www.oracle.com (www.oracle.com)... 23.34.225.55
Connecting to www.oracle.com (www.oracle.com)|23.34.225.55|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: `/tmp/oab-download.html'

```
 0K .......... .......... .......... .......... ..........  342K
50K .......... .......... .......... .......... ..........  492K
```

   100K .......... .......... .......... .......... ..........  732K
   150K .......... .                                           1.52M=0.3s

2012-08-16 01:06:05 (500 KB/s) - `/tmp/oab-download.html' saved [165411]

13715's retcode: 0
success
 [x] Downloading jdk-7u5-linux-i586.tar.gz :    http://: Invalid host name.
13733's retcode: 1
failed

**Comment by miniworm** [comment]
I see that you haven't changed everything needed - your log says that it tries to download jdk-7u5-linux-i586.tar.gz but it should be jdk-7u6-linux-i586.tar.gz. Check if you have latest oab-java.sh and that you applied changes in all 3 places described by me above:

1.
DEB_VERSION=7.6-1

2.
JAVA_VER=7
JAVA_UPD=6

3.
wget http://www.oracle.com/technetwork/java/javase/downloads/jdk6-downloads-1637591.html -O /tmp/oab-download.html >> "$log" 2>&1 &

**Comment by spage25** [comment]
Thanks miniworm, I had build error too but i didn't have the latest script.

**Comment by spage25** [comment]
Tested on 10.04 and 12.04 amd64.

**Comment by flexiondotorg** [comment]
Hi,

I just retested 0.2.5 of the script and it successfully built Java 6 and 7. This issue was as a result of new releases by Oracle and the upstream packing scripts catching up.

Regards, Martin.
