### ISSUE TITLE
Moving the packages failed on 64bit system

### ISSUE THREAD

**Issue by scic** [flexiondotorg/oab-java6#6]
I'm on Ubuntu 11.10 64bit.
# Build information

TOP         = usr/lib/jvm
VENDOR      = sun
RELEASE     = 6
PRODUCT     = java6
basename    = sun-java6
version     = 6
releng_ver  = 30
unpackdir   = jdk1.6.0_30
srcdir      = x64-jdk
all_archs   = i586 x64
arch        = x64
archdir     = amd64
bin_pattern = jdk-6u30-linux-%.bin

rm -rf jdk1.6.0_30
binsize=$(wc -c jdk-6u30-linux-i586.bin | awk '{print $1}'); \
        zipstart=$(unzip -ql jdk-6u30-linux-i586.bin 2>&1 >/dev/null | sed -n -e 's/.\* ([0-9][0-9]_) extra bytes._/\1/p'); \
        tail -c $(expr $binsize - $zipstart) jdk-6u30-linux-i586.bin > tmp-jdk.zip
unzip -q tmp-jdk.zip
mv jdk1.6.0_30 i586-jdk
i586
diff -u i586-jdk/LICENSE i586-jdk/jre/LICENSE
diff -u i586-jdk/THIRDPARTYLICENSEREADME.txt \
            i586-jdk/jre/THIRDPARTYLICENSEREADME.txt
set -e; \
        for i in $(find i586-jdk -name '_.pack'); do \
          i586-jdk/bin/unpack200 $i \
                $(dirname $i)/$(basename $i .pack).jar; \
          rm -f $i; \
        done
/bin/bash: line 2: i586-jdk/bin/unpack200: No such file or directory
make: *_\* [unpack-i586-stamp] Fehler 1
dpkg-buildpackage: Fehler: Fehler-Exitstatus von debian/rules build war 2
^H^H9285's retcode: 2
success
 [x] Moving the packages mv: Aufruf von stat für „/var/local/oab/sun-java6_6.30-4~oneiric1_amd64.changes“ nicht möglich: Datei oder Verzeichnis nicht gefunden
  mv: Aufruf von stat für „/var/local/oab/_sun-java6-__6.30-4~oneiric1_*.deb“ nicht möglich: Datei oder Verzeichnis nicht gefunden
^H^H9614's retcode: 1
failed

**Comment by flexiondotorg** [comment]
Hi,

It looks like the downloaded Java packages from Oracle might be corrupt? Can you run the script (v0.1.6) again and see if it works this time?

Regards, Martin.

**Comment by beruic** [comment]
This might be my issue as well. I ran the new version of the script, but packages doesn't get updated in the update-manager.

**Comment by beruic** [comment]
Re-running the script today helped my issue.

**Comment by flexiondotorg** [comment]
Hi,

Thanks for the feedback. I'll assume this was due to corrupt downloads and close this ticket.

Regards, Martin.

**Comment by beruic** [comment]
Some error message/handling would be nice when this happens. Would also be cool if scic would report back if his issue is resolved as well.

**Comment by flexiondotorg** [comment]
Error handling for this issue was added in 0.1.8 as wel :-)

**Comment by scic** [comment]
The new version did not solve my problem. But I further investigated the issue. Seems I can neither install the 32bit version of java manually.
I downloaded ./jre-6u30-linux-i586.bin (its the older version) executed it and got: "./install.sfx.7205: not found"
Could it be that the issue is that an archive extracted with my 64bit unpack200 version is always broken?

I have: 
java version "1.6.0_23"  
OpenJDK Runtime Environment (IcedTea6 1.11pre) (6b23~pre11-0ubuntu1.11.10.1)  
OpenJDK 64-Bit Server VM (build 20.0-b11, mixed mode) 

and unpack200 version 1.31, 08/01/25

**Comment by beruic** [comment]
Perhaps you should delete the /var/local/oab/ directory, and run again, to make sure you have no broken files. You are running with sudo, right?

**Comment by scic** [comment]
I deleted the directory, used the latest version, run it with sudo and i got the follwing error:

TOP         = usr/lib/jvm
VENDOR      = sun
RELEASE     = 6
PRODUCT     = java6
basename    = sun-java6
version     = 6
releng_ver  = 31
unpackdir   = jdk1.6.0_31
srcdir      = x64-jdk
all_archs   = i586 x64
arch        = x64
archdir     = amd64
bin_pattern = jdk-6u31-linux-%.bin

rm -rf jdk1.6.0_31
binsize=$(wc -c jdk-6u31-linux-i586.bin | awk '{print $1}'); \
        zipstart=$(unzip -ql jdk-6u31-linux-i586.bin 2>&1 >/dev/null | sed -n -e 's/.\* ([0-9][0-9]_) extra bytes._/\1/p'); \
        tail -c $(expr $binsize - $zipstart) jdk-6u31-linux-i586.bin > tmp-jdk.zip
unzip -q tmp-jdk.zip
mv jdk1.6.0_31 i586-jdk
i586
diff -u i586-jdk/LICENSE i586-jdk/jre/LICENSE
diff -u i586-jdk/THIRDPARTYLICENSEREADME.txt \
            i586-jdk/jre/THIRDPARTYLICENSEREADME.txt
set -e; \
        for i in $(find i586-jdk -name '_.pack'); do \
          i586-jdk/bin/unpack200 $i \
                $(dirname $i)/$(basename $i .pack).jar; \
          rm -f $i; \
        done
/bin/bash: line 2: i586-jdk/bin/unpack200: No such file or directory
make: *_\* [unpack-i586-stamp] Fehler 

When i look in the directory /var/local/oab/src/i586-jdk/bin/unpack200. The unpack200 file is there.

find i586-jdk -name '*.pack' Returns (from /var/local/oab/src directory):
i586-jdk/jre/lib/javaws.pack
i586-jdk/jre/lib/deploy.pack
i586-jdk/jre/lib/plugin.pack
i586-jdk/jre/lib/charsets.pack
i586-jdk/jre/lib/rt.pack
i586-jdk/jre/lib/ext/localedata.pack
i586-jdk/jre/lib/jsse.pack
i586-jdk/lib/tools.pack

Manually unpacking these files with the unpack200 in i586-jdk seems to work.
