### ISSUE TITLE
wget error :: Critical Error

### ISSUE THREAD

**Issue by imrasalghul** [flexiondotorg/oab-java6#64]
Downloading jdk-6u35-linux-i586.bin :    http://: Invalid host name.

**Comment by panchmp** [comment]
Now latest version is 6u37, but script try download 6u35 as latest

 [x] Installing Java build requirements success
 [x] Making build directories success
 [x] Removing clones of https://github.com/rraptorr/sun-java6 success
 [x] Cloning https://github.com/rraptorr/sun-java6 success
 [x] Checking out v6.35-1 success
 [x] Getting Java SE download page success
 [x] Getting current release download page success
 [x] Getting previous releases download page success
 [x] Downloading jdk-6u35-linux-i586.bin :  failed
 [i] Showing the last 5 lines from the logfile (/home/michael/oab-java.sh.log)...
6514's retcode: 0
success
 [x] Downloading jdk-6u35-linux-i586.bin :    http://: Invalid host name.
6532's retcode: 1
failed

**Comment by Humphreybas** [comment]
I guess the script decides to download 6u35 since 6u37 is not supported in debian?
The problem however is that 6u35 does not exist on the archive page of oracle (http://www.oracle.com/technetwork/java/javasebusiness/downloads/java-archive-downloads-javase6-419409.html) nor in the frontpage (http://www.oracle.com/technetwork/java/javase/downloads/index.html). This seems to be a bug in the oracle site?

Correction: now suddenly it does try to download 6u37 but somehow it does not succeed in finding the download url from the frontpage and then looks for it on the archive page where it is not present for sure.

**Comment by panchmp** [comment]
Why is 6u37 not supported in debian?

**Comment by Humphreybas** [comment]
As I stated in the correction it is trying to download the 6u37 now so forget about the 'not supporting' part.
The reason I said that was because in the script it says:

```
# Determine the currently supported Java version and update
JAVA_VER=`echo ${DEB_VERSION} | cut -d'.' -f1`
JAVA_UPD=`echo ${DEB_VERSION} | cut -d'.' -f2 | cut -d'-' -f1`
```

**Comment by trumbitta** [comment]
+1 not working for me exactly as in https://github.com/flexiondotorg/oab-java6/issues/64#issuecomment-9522683

**Comment by elazar** [comment]
+1. The latest version listed in download.html is 34, versus 37 that it's currently using. Manually changing `JAVA_UPD` to be assigned `"34"` gets it at least as fair as attempting to build, though I get another failure at that point.

```
make: *** No rule to make target `unpack-i586-stamp', needed by `unpack-stamp'.  Stop.
dpkg-buildpackage: error: debian/rules build gave error exit status 2
11087's retcode: 2
```

**Comment by chengluo** [comment]
if you want to use it for oracle-java-7u9, you need modify the script as
diff --git a/oab-java.sh b/oab-java.sh
index 0f50c00..c384a67 100755
--- a/oab-java.sh
+++ b/oab-java.sh
@@ -450,7 +450,7 @@ if [ -z "${DOWNLOAD_FOUND}" ]; then
     if [ "${JAVA_UPSTREAM}" == "sun-java6" ]; then
         wget http://www.oracle.com/technetwork/java/javasebusiness/downloads/java-archive-downloads-javase6-419409.h
     else
-        wget http://www.oracle.com/technetwork/java/javasebusiness/downloads/java-archive-downloads-javase7-521261.h
-        wget http://www.oracle.com/technetwork/java/javase/downloads/jdk7u9-downloads-1859576.html -O /tmp/oab-downl
   fi
   pid=$!;progress $pid
  fi

to get the right download url.

**Comment by imrasalghul** [comment]
I'll fork this project and assume responsibility since we haven't heard from the developer even though dozens of people complained about the issue.

**Comment by imrasalghul** [comment]
Pull request closed.
