### ISSUE TITLE
failed to download

### ISSUE THREAD

**Issue by francescor** [flexiondotorg/oab-java6#65]
W: Failed to fetch http://ppa.launchpad.net/kazam-team/unstable-series/ubuntu/dists/lucid/main/binary-amd64/Packages.gz

E: Some index files failed to download, they have been ignored, or old ones used instead.
21255's retcode: 100
failed

on a 

lsb_release -a
LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 10.04.4 LTS
Release:    10.04
Codename:   lucid

**Comment by flexiondotorg** [comment]
Hi,

This is not a bug with the script. You have a defunct PPA in your apt sources.

Regards, Martin.
