### ISSUE TITLE
failure to compile repo

### ISSUE THREAD

**Issue by raziel23x** [flexiondotorg/oab-java6#67]
rm -f debian/shlibs.local
rm -f debian/sun-java6-bin.substvars
dh_shlibdeps \
        -lusr/lib/jvm/java-6-sun-1.6.0.37/jre/lib/amd64/server \
        -Xlibjavaplugin_oji.so -Xlibnpjp2.so \
        -- --warnings=0
dpkg-shlibdeps: warning: Can't extract name and version from library name `libjvm.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name`libjvm.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name `libjava.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name`libjava.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name `libjvm.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name`libjvm.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name `libjava.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name`libjava.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name `libjvm.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name`libjvm.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name `libjli.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name`libjli.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name `libjvm.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name`libjvm.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name `libjava.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name`libjava.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name `libjvm.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name`libjvm.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name `libawt.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name`libawt.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name `libjava.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name`libjava.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name `libjvm.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name`libjvm.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name `libjava.so'
dpkg-shlibdeps: warning: Can't extract name and version from library name`libjava.so

**Comment by raziel23x** [comment]
was resolved by manually doing 
sudo apt-get install libdistro-info-perl
Ubuntu 12.10

**Comment by raziel23x** [comment]
spoke too soon

http://pastebin.com/gL36mEmd

**Comment by flexiondotorg** [comment]
I've just test with Lucid, Precise and Ringtail and everything is working correctly.
