### ISSUE TITLE
git clone vs wget

### ISSUE THREAD

**Issue by J--** [flexiondotorg/oab-java6#68]
Another github publisher, pylanglois, offers a tweak to your instructions.  For your consideration:

hxxp://gaggl.com/2012/04/installing-java6-jdk-on-ubuntu-12-04/comment-page-1/#comment-1469

sudo apt-get purge sun-java
mkdir ~/src_SunJava6
cd ~/src_SunJava6
git clone https://github.com/flexiondotorg/oab-java6.git
cd ~/src_SunJava6/oab-java6
sudo ./oab-java.sh -c

sudo apt-get install sun-java6-jre sun-java6-plugin sun-java6-bin sun-java6-jdk

I have slightly changed the target directory for scrape sanity and defaulted to -c.   It is not clear the advantage of installing also " sun-java6-bin sun-java6-jdk"  unless one needed the jdk, too? 

Can -7 and -c be combined?

Can not lines 2-5 be consolidated (without &&) specifying target directory with git command? [git help clone]. This seems to play nicely:

sudo apt-get purge sun-java
git clone https://github.com/flexiondotorg/oab-java6.git ~/src_SunJava6
sudo ~/src_SunJava6/oab-java.sh -c

No oab-java6  directory will be created as location is specified to git.

**Comment by flexiondotorg** [comment]
Hi,

Thanks for you feedback, but the instructions are written that way so the script can be used by someone who does not have git installed.

Regards, Martin.
