### ISSUE TITLE
update-alternatives warning

### ISSUE THREAD

**Issue by J--** [flexiondotorg/oab-java6#69]
I'm not clear what's happening so here's all the text bits.

Setting up sun-java6-bin (6.37-1~oneiric1) ...
update-alternatives: using /usr/lib/jvm/java-6-sun/jre/bin/ControlPanel to provide /usr/bin/ControlPanel (ControlPanel) in auto mode.
update-alternatives: warning: alternative /usr/lib/jvm/java-7-openjdk-i386/jre/bin/java (part of link group java) doesn't exist. Removing from list of alternatives.
update-alternatives: using /usr/lib/jvm/java-6-sun/jre/bin/java_vm to provide /usr/bin/java_vm (java_vm) in auto mode.
update-alternatives: using /usr/lib/jvm/java-6-sun/jre/bin/javaws to provide /usr/bin/javaws (javaws) in auto mode.
update-alternatives: using /usr/lib/jvm/java-6-sun/jre/bin/jcontrol to provide /usr/bin/jcontrol (jcontrol) in auto mode.
update-alternatives: warning: alternative /usr/lib/jvm/java-7-openjdk-i386/jre/bin/keytool (part of link group keytool) doesn't exist. Removing from list of alternatives.
update-alternatives: warning: alternative /usr/lib/jvm/java-7-openjdk-i386/jre/bin/pack200 (part of link group pack200) doesn't exist. Removing from list of alternatives.
update-alternatives: warning: alternative /usr/lib/jvm/java-7-openjdk-i386/jre/bin/policytool (part of link group policytool) doesn't exist. Removing from list of alternatives.
update-alternatives: warning: alternative /usr/lib/jvm/java-7-openjdk-i386/jre/bin/rmid (part of link group rmid) doesn't exist. Removing from list of alternatives.
update-alternatives: warning: alternative /usr/lib/jvm/java-7-openjdk-i386/jre/bin/rmiregistry (part of link group rmiregistry) doesn't exist. Removing from list of alternatives.
update-alternatives: warning: alternative /usr/lib/jvm/java-7-openjdk-i386/jre/bin/unpack200 (part of link group unpack200) doesn't exist. Removing from list of alternatives.
update-alternatives: warning: alternative /usr/lib/jvm/java-7-openjdk-i386/jre/bin/orbd (part of link group orbd) doesn't exist. Removing from list of alternatives.
update-alternatives: warning: alternative /usr/lib/jvm/java-7-openjdk-i386/jre/bin/servertool (part of link group servertool) doesn't exist. Removing from list of alternatives.
update-alternatives: warning: alternative /usr/lib/jvm/java-7-openjdk-i386/jre/bin/tnameserv (part of link group tnameserv) doesn't exist. Removing from list of alternatives.
update-alternatives: warning: alternative /usr/lib/jvm/java-7-openjdk-i386/jre/lib/jexec (part of link group jexec) doesn't exist. Removing from list of alternatives.
Setting up sun-java6-jre (6.37-1~oneiric1) ...
Setting up sun-java6-plugin (6.37-1~oneiric1) ...
Processing triggers for menu ...

... previously...

 [x] Installing Java build requirements success
 [x] Making build directories success
 [x] Removing clones of https://github.com/rraptorr/sun-java6 success
 [x] Cloning https://github.com/rraptorr/sun-java6 success
 [x] Checking out v6.37-1 success
 [x] Getting Java SE download page success
 [x] Getting current release download page success
 [x] Downloading jdk-6u37-linux-i586.bin : 68.44 MB success
 [x] Symlinking jdk-6u37-linux-i586.bin success
 [x] Downloading jdk-6u37-linux-x64.bin : 68.71 MB success
 [x] Symlinking jdk-6u37-linux-x64.bin success
 [x] Getting Java Cryptography Extension download page success
 [x] Downloading jce_policy-6.zip : 8.89 KB success
 [x] Symlinking jce_policy-6.zip success
 [x] Updating the changelog success
 [x] Building the packages success
 [x] Removing existing .deb packages success
 [x] Moving the packages success
 [x] Creating Packages.gz file success
 [x] Creating Release file success
 [x] Signing the 'Release' file success
 [x] Exporting public key success
 [x] Adding public key success
 [x] Update package list success
All done!
me@hooray:~/srcSafely$ sudo apt-get install sun-java6-jre sun-java6-plugin sun-java6-bin
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following extra packages will be installed:
  gsfonts-x11
Suggested packages:
  sun-java6-fonts ttf-baekmuk ttf-unfonts-core ttf-kochi-gothic
  ttf-sazanami-gothic ttf-kochi-mincho ttf-sazanami-mincho ttf-arphic-uming
The following NEW packages will be installed:
  gsfonts-x11 sun-java6-bin sun-java6-jre sun-java6-plugin
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 9,108 B/36.7 MB of archives.
After this operation, 104 MB of additional disk space will be used.
Do you want to continue [Y/n]? y
Get:1 http://us.archive.ubuntu.com/ubuntu/ oneiric/main gsfonts-x11 all 0.22 [9,108 B]
Fetched 9,108 B in 2s (3,741 B/s)
Selecting previously deselected package gsfonts-x11.
(Reading database ... 389068 files and directories currently installed.)
Unpacking gsfonts-x11 (from .../gsfonts-x11_0.22_all.deb) ...
Selecting previously deselected package sun-java6-jre.
Unpacking sun-java6-jre (from .../sun-java6-jre_6.37-1~oneiric1_all.deb) ...
Selecting previously deselected package sun-java6-bin.
Unpacking sun-java6-bin (from .../sun-java6-bin_6.37-1~oneiric1_i386.deb) ...
Selecting previously deselected package sun-java6-plugin.
Unpacking sun-java6-plugin (from .../sun-java6-plugin_6.37-1~oneiric1_i386.deb) ...
Processing triggers for fontconfig ...
Processing triggers for shared-mime-info ...
Unknown media type in type 'all/all'
Unknown media type in type 'all/allfiles'
Unknown media type in type 'uri/mms'
Unknown media type in type 'uri/mmst'
Unknown media type in type 'uri/mmsu'
Unknown media type in type 'uri/pnm'
Unknown media type in type 'uri/rtspt'
Unknown media type in type 'uri/rtspu'
Unknown media type in type 'interface/x-winamp-skin'
Processing triggers for menu ...
Processing triggers for desktop-file-utils ...
Processing triggers for gnome-menus ...
Processing triggers for bamfdaemon ...
Rebuilding /usr/share/applications/bamf.index...
Setting up gsfonts-x11 (0.22) ...
Setting up sun-java6-bin (6.37-1~oneiric1) ...

**Comment by flexiondotorg** [comment]
I've just tested this on Lucid, Precise and Raring and everything works correctly.
