### ISSUE TITLE
Downloading JDK Broken

### ISSUE THREAD

**Issue by SeeJayEmm** [flexiondotorg/oab-java6#72]
It appears that the downloads are broken again. Building fails, log snipped attached. Also files downloaded are the wrong size:

root@saffron:/var/local/oab/pkg# ls -l jdk-7*
-rw-r--r-- 1 root staff 2051 2012-12-11 17:03 jdk-7u9-linux-i586.tar.gz
-rw-r--r-- 1 root staff 2051 2012-12-11 17:03 jdk-7u9-linux-x64.tar.gz
# Build information

TOP         = usr/lib/jvm
VENDOR      = oracle
RELEASE     = 7
PRODUCT     = java7
basename    = oracle-java7
version     = 7
releng_ver  = 9
unpackdir   = jdk1.7.0_09
srcdir      = x64-jdk
all_archs   = i586 x64
arch        = x64
archdir     = amd64
bin_pattern = jdk-7u9-linux-%.tar.gz

rm -rf jdk1.7.0_09
tar xf jdk-7u9-linux-i586.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make: **\* [unpack-i586-stamp] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2                                                   585's retcode: 2

**Comment by 2ndactinnovations** [comment]
Error comes from git tagging that returns the tags ordered by name (so v7.10 comes first when we expected it last). One temporary fix is to replace the line git tag -l | tail -n1 by git tag -l 'v7.1*' | tail - n1 (line 421). This will be ok I believe for all v7 updates till it reaches v7.2x

**Comment by eugenp** [comment]
Bumping into the same problem - the workaround did not work either: 

```
 [x] Checking out ==> standard input <==
v7.10-1 failed
 [i] Showing the last 5 lines from the logfile (/home/ubuntu/oab-java.sh.log)...
error: pathspec 'input' did not match any file(s) known to git.
error: pathspec '<==' did not match any file(s) known to git.
error: pathspec 'v7.10-1' did not match any file(s) known to git.                                                                                                                                                          28642's retcode: 1
failed
```

**Comment by ehsanullahjan** [comment]
I also got this error when trying to install Java 7 on Ubuntu 12.04.

**Comment by ghost** [comment]
Guys has anyone found a workaround for this issue?

**Comment by SeeJayEmm** [comment]
I manually downloaded the missing files into /var/local/oab/pkg

jdk-7u9-linux-i586.tar.gz
jdk-7u9-linux-x64.tar.gz

This allowed the build to complete.

**Comment by drdamour** [comment]
I got this issue to when trying to run with the -7 switch. the tar's downloaded are HTML files with this relevant text: 

<div class="message-row">
      <p class="loginFailed">System error. Please re-try your action. If you continue to get this error, please contact the Administrator.</p>
</div>

manually downloading the tar's from http://www.oracle.com/technetwork/java/javase/downloads/jdk7u9-downloads-1859576.html and placing them in /var/local/oab/pkg  was a successful work around.

maybe the script should do an MD5 check before trying to untar?

**Comment by helterscelter** [comment]
at least one comment on the pull request rywall referenced above indicates that the patch may fix this issue as well. (based on the conversation above it makes sense that this would be the case)
https://github.com/flexiondotorg/oab-java6/issues/75
