### ISSUE TITLE
Ubuntu packaging does not provide 'default-jre'

### ISSUE THREAD

**Issue by phobos182** [flexiondotorg/oab-java6#73]
Because of this, packages which require 'default-jre', or 'default-jdk' will install OpenJDK on Ubuntu.

**Comment by phobos182** [comment]
This is what it currently provides.

java6-runtime-headless java6-runtime java5-runtime-headless java5-runtime java2-runtime-headless java2-runtime java-virtual-machine java-runtime-headless java-runtime 

We should include 'default-jre' & 'default-jre-headless' in addition.

**Comment by flexiondotorg** [comment]
Please raise this issue in the upstream Debian packaging projects, it is not something I can influence with my script.
- https://github.com/rraptorr/sun-java6
- https://github.com/rraptorr/oracle-java7

Regards, Martin,

**Comment by phobos182** [comment]
Updating this issue. This was an error on my end. This package does provide default-jre.
