### ISSUE TITLE
31367's retcode: 100

### ISSUE THREAD

**Issue by marty494** [flexiondotorg/oab-java6#76]
System: Ubuntu 12.04.1 LTS (32 bit)

W: Failed to fetch http://ppa.launchpad.net/sun-java-community-team/sun-java6/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found
1. git clone https://github.com/flexiondotorg/oab-java6.git
2. ./oab-java6/oab-java.sh
3. Output...

oab-java.sh v0.2.6 - Create a local 'apt' repository for Sun Java 6 and/or Oracle Java 7 packages.

Copyright (c) Martin Wimpress, http://flexion.org. MIT License

By running this script to download Java you acknowledge that you have
read and accepted the terms of the Oracle end user license agreement.
- http://www.oracle.com/technetwork/java/javase/terms/license/

If you want to see what this is script is doing while it is running then execute
the following from another shell:

  tail -f /root/oab-java.sh.log

 [x] Installing Java build requirements success
 [x] Making build directories success
 [x] Removing clones of https://github.com/rraptorr/sun-java6 success
 [x] Cloning https://github.com/rraptorr/sun-java6 success
 [x] Checking out v6.38-1 success
 [x] Getting Java SE download page success
 [x] Getting current release download page success
 [x] Downloading jdk-6u38-linux-i586.bin : 68.45 MB success
 [x] Symlinking jdk-6u38-linux-i586.bin success
 [x] Downloading jdk-6u38-linux-x64.bin : 68.72 MB success
 [x] Symlinking jdk-6u38-linux-x64.bin success
 [x] Getting Java Cryptography Extension download page success
 [x] Downloading jce_policy-6.zip : 8.89 KB success
 [x] Symlinking jce_policy-6.zip success
 [x] Updating the changelog success
 [x] Building the packages success
 [x] Moving the packages success
 [x] Creating Packages.gz file success
 [x] Creating Release file success
 [x] Signing the 'Release' file success
 [x] Exporting public key success
 [x] Adding public key success
 [x] Update package list failed
 [i] Showing the last 5 lines from the logfile (/root/oab-java.sh.log)...
W: Failed to fetch http://ppa.launchpad.net/sun-java-community-team/sun-java6/ubuntu/dists/precise/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
31367's retcode: 100
failed

**Comment by flexiondotorg** [comment]
Hi,

This is not a bug in the script. You have a defunct PPA in your apt sources.

Regards, Martin.
