### ISSUE TITLE
Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/a/apparmor/dh-apparmor_2.7.102-0ubuntu3.2_all.deb

### ISSUE THREAD

**Issue by ghost** [flexiondotorg/oab-java6#78]
sudo ./oab-java.sh
oab-java.sh v0.2.6 - Create a local 'apt' repository for Sun Java 6 and/or Oracle Java 7 packages.

Copyright (c) Martin Wimpress, http://flexion.org. MIT License

By running this script to download Java you acknowledge that you have
read and accepted the terms of the Oracle end user license agreement.
- http://www.oracle.com/technetwork/java/javase/terms/license/

If you want to see what this is script is doing while it is running then execute
the following from another shell:

  tail -f /home/koenraad/src/oab-java6/oab-java.sh.log

 [x] Installing Java build requirements failed
 [i] Showing the last 5 lines from the logfile (/home/koenraad/src/oab-java6/oab-java.sh.log)...
  404  Not Found [IP: 91.189.92.200 80]
Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/a/apparmor/dh-apparmor_2.7.102-0ubuntu3.2_all.deb  404  Not Found [IP: 91.189.92.200 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
5315's retcode: 100
failed

Tied Several time but it won't work please help .

**Comment by flexiondotorg** [comment]
Hi,

This error mesage seem to indicate that apt-get is not able to install the required packages. This is not a problem something the script caused o can fix.

Regards, Martin,
