### ISSUE TITLE
Libreoffice does not find JVM

### ISSUE THREAD

**Issue by FranzXaver** [flexiondotorg/oab-java6#79]
![Bildschirmfoto - 02 01 2013 - 14:13:24](https://f.cloud.github.com/assets/2254105/38291/360e857e-54de-11e2-99cb-5c99c1b902a2.png)
I am using Xubuntu 12.10 and the latest version of this script.
I have successfully built Java 6 and installed the packages:

ii  sun-java6-bin                        6.38-1~quantal1         i386 
ii  sun-java6-jdk                        6.38-1~quantal1         i386  
ii  sun-java6-jre                        6.38-1~quantal1         all  

Unfortunately Libreoffice cannot find a JVM on the system, also manually adding the JVM does not work. 

"javaldx: Could not find a Java Runtime Environment! 
Please ensure that a JVM and the package libreoffice-java-common
is installed.
If it is already installed then try removing ~/.libreoffice/3/user/config/javasettings_Linux_*.xml
Warning: failed to read path from javaldx"

What am I doing wrong?

**Comment by flexiondotorg** [comment]
Hi,

What does `java -version` return.

Regards, Martin.

**Comment by FranzXaver** [comment]
$ java -version
java version "1.6.0_39"
Java(TM) SE Runtime Environment (build 1.6.0_39-b04)
Java HotSpot(TM) Server VM (build 20.14-b01, mixed mode)

**Comment by flexiondotorg** [comment]
Hi,

In which case, the script did it's job. You have Java installed and it is in the path. I can't really help anymore than that. Sorry :-(

Regards, Martin.

**Comment by FranzXaver** [comment]
Thanks, it seems to be an issue with Libreoffice. Keep up the good work!

**Comment by FranzXaver** [comment]
FYI, this is now fixed with Libreoffice 4.0
