### ISSUE TITLE
Download path have changed

### ISSUE THREAD

**Issue by beruic** [flexiondotorg/oab-java6#8]
I cannot update to Java 6 Update 31 on my system. The files from sun gets a 404 when trying to download.
As far as I can see, it's the file name convention that has changed.
http://www.oracle.com/technetwork/java/javase/downloads/jdk-6u31-download-1501634.html

**Comment by flexiondotorg** [comment]
Hi,

A fix is coming today :-)

Regards, Martin.

**Comment by mikkorantalainen** [comment]
Line 260: JAVA_REL="b04" is enough to fix this issue. It would be really nice to be able to not hardcode this value.
