### ISSUE TITLE
Problem installing build requirements without --force-yes in 0.2.7

### ISSUE THREAD

**Issue by hanshook** [flexiondotorg/oab-java6#86]
On a fresh Ubuntu 12.04 server install I had to change line 401 of version 0.2.7
from
apt-get install -y --no-install-recommends ${BUILD_DEPS} >> "$log" 2>&1 &
to 
apt-get install -y --force-yes --no-install-recommends ${BUILD_DEPS} >> "$log" 2>&1 &

Then it works like a charm again!

Regards 

Hans Höök

**Comment by flexiondotorg** [comment]
Just tested on Lucid, Precise and Raring and everything worked correctly.
