### ISSUE TITLE
Unable to finish

### ISSUE THREAD

**Issue by denser** [flexiondotorg/oab-java6#87]
[x] Installing Java build requirements success
 [x] Making build directories success
 [x] Removing clones of https://github.com/rraptorr/sun-java6 success
 [x] Cloning https://github.com/rraptorr/sun-java6 success
 [x] Checking out v6.39-1 success
 [x] Getting Java SE download pagesuccess
 [x] Getting previous releases download page success
 [x] Downloading jdk-6u39-linux-i586.bin :  failed
 [i] Showing the last 5 lines from the logfile (/root/oab-java6.sh.log)...                                                                     29704's retcode: 0
success
 [x] Downloading jdk-6u39-linux-i586.bin :    http://: Invalid host name.                                                                      29724's retcode: 1
failed

**Comment by flexiondotorg** [comment]
Just tested Lucid, Precise and Raring and everything worked correctly.
