### ISSUE TITLE
ia32-libs has been removed from Ubuntu 12.04

### ISSUE THREAD

**Issue by rywall** [flexiondotorg/oab-java6#89]
This causes the installation to fail on 64-bit 12.04 because it tries to install ia32-libs.

See: http://askubuntu.com/questions/107230/what-happened-to-the-ia32-libs-package

It seems to install just fine when I removed ia32-libs as a dependency.

**Comment by mateor** [comment]
Did you `sudo apt-get install update` ? I have been using this script to get the JDK on my servers with no problem, all of which are using the 12.04 64-bit image.

I have had no problems installing that package.

**Comment by eugenp** [comment]
I am seeing the same problem on an Ubuntu 12.10 64bit.

**Comment by michaelhood** [comment]
Also seeing it here on an updated 12.10 x64.

**Comment by michaelhood** [comment]
It looks like this is [intended to be] addressed in the script already:

``` bash
if grep -q ia32 ${WORK_PATH}/src/debian/rules; then
    # Upstream still builds ia32 package, download both architectures
    JAVA_BINS="jdk-${JAVA_VER}u${JAVA_UPD}-linux-i586${JAVA_EXT} jdk-${JAVA_VER}u${JAVA_UPD}-linux-x64${JAVA_EXT}"
else
    # Upstream has removed ia32 package, just download the appropriate one
    if [ "${LSB_ARCH}" == "amd64" ]; then
        JAVA_BINS="jdk-${JAVA_VER}u${JAVA_UPD}-linux-x64${JAVA_EXT}"
    else
        JAVA_BINS="jdk-${JAVA_VER}u${JAVA_UPD}-linux-i586${JAVA_EXT}"
    fi
fi
```

but before it ever gets there:

``` bash
if [ "${LSB_ARCH}" == "amd64" ]; then
    BUILD_DEPS="${BUILD_DEPS} lib32asound2 ia32-libs"
fi

if [ "${JAVA_UPSTREAM}" == "oracle-java7" ]; then
    BUILD_DEPS="${BUILD_DEPS} libxrender1"
fi

# Install the Java build requirements
ncecho " [x] Installing Java build requirements "
apt-get install -y --no-install-recommends ${BUILD_DEPS} >> "$log" 2>&1 &
```

**Comment by mateor** [comment]
After I ran this on probably 10 different ubuntu versions, I finally encountered this on 12.04.2. It can be gotten around with the info one post above, but I was even more quickly able to run the script by
    `sudo apt-get install libgl1-mesa-dri:i386`

**Comment by shortdudey123** [comment]
I am having the same issue 12.04 (not 12.04.2).  When I tried mateor's solution above, i get a depends error.

```
# apt-get install libgl1-mesa-dri:i386 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgl1-mesa-dri:i386 : Depends: libdrm-intel1:i386 (>= 2.4.27) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by flexiondotorg** [comment]
I've tested this is Lucid, Precise and Ringtail. All is working correctly and `ia32-libs` is available in the official repos for all those releases.

**Comment by shortdudey123** [comment]
If you tested it, can you provide the solution then?

**Comment by mblair** [comment]
Can this be re-opened? This is definitely broken on Saucy; `ia32-libs` isn't in the Canonical repo.
