### ISSUE TITLE
Downloading jdk-6u41-linux-i586.bin  : failed

### ISSUE THREAD

**Issue by AchuM** [flexiondotorg/oab-java6#90]
root@root:~# sudo ./oab-java6.sh
oab-java6.sh v0.2.1 - Create a local 'apt' repository for Ubuntu Java packages.
Copyright (c) Martin Wimpress, http://flexion.org. MIT License

By running this script to download Java you acknowledge that you have
read and accepted the terms of the Oracle end user license agreement.
- http://www.oracle.com/technetwork/java/javase/terms/license/

If you want to see what this is script is doing while it is running then execute
the following from another shell:

  tail -f /root/oab-java6.sh.log

 [x] Installing Java build requirements success
 [x] Making build directories success
 [x] Removing clones of https://github.com/rraptorr/sun-java6 success
 [x] Cloning https://github.com/rraptorr/sun-java6 success
 [x] Checking out v6.41-1 success
 [x] Getting Java SE download pagesuccess
 [x] Getting previous releases download page success
 [x] Downloading jdk-6u41-linux-i586.bin :  failed
 [i] Showing the last 5 lines from the logfile (/root/oab-java6.sh.log)...
22404's retcode: 0
success
 [x] Downloading jdk-6u41-linux-i586.bin :    http://: Invalid host name.
22421's retcode: 1
failed

**Comment by danielmagnussons** [comment]
I ran the script a few times and it started working, download problems?

**Comment by flexiondotorg** [comment]
Just tested on Lucid, Precise and Raring and all is working well.
