### ISSUE TITLE
ERROR! Packages failed to build.

### ISSUE THREAD

**Issue by WimLeys** [flexiondotorg/oab-java6#91]
Hi Martin,

I have Java 7 running on another Ubuntu computer. Just installed Ubuntu 12.04.2 LTS on this computer. On this one I can't get Java 6 nor 7 installed. 

:~$ sudo ./oab-java.sh -7 -coab-java.sh v0.2.5 - Create a local 'apt' repository for Sun Java 6 and/or Oracle Java 7 packages.

Copyright (c) Martin Wimpress, http://flexion.org. MIT License

By running this script to download Java you acknowledge that you have
read and accepted the terms of the Oracle end user license agreement.
- http://www.oracle.com/technetwork/java/javase/terms/license/

If you want to see what this is script is doing while it is running then execute
the following from another shell:

  tail -f /home/wim/oab-java.sh.log

 [x] Installing Java build requirements success
 [x] Making build directories success
 [x] Removing clones of https://github.com/rraptorr/oracle-java7 success
 [x] Cloning https://github.com/rraptorr/oracle-java7 success
 [x] Checking out v7.9-1 success
 [x] Getting Java SE download page success
 [x] Getting current release download page success
 [x] Getting previous releases download page success
 [x] Downloading jdk-7u9-linux-i586.tar.gz : 92.85 MB success
 [x] Symlinking jdk-7u9-linux-i586.tar.gz success
 [x] Downloading jdk-7u9-linux-x64.tar.gz : 91.59 MB success
 [x] Symlinking jdk-7u9-linux-x64.tar.gz success
 [x] Getting Java Cryptography Extension download page success
 [x] Downloading UnlimitedJCEPolicyJDK7.zip : 7.3 K success
 [x] Symlinking UnlimitedJCEPolicyJDK7.zip success
 [x] Updating the changelog success
 [x] Building the packages success
ERROR! Packages failed to build.

**Comment by ushkinaz** [comment]
Same here.
Log file has following entries at the end:

rm -rf jdk1.6.0_41  
binsize=$(wc -c jdk-6u41-linux-i586.bin | awk '{print $1}'); \  
    zipstart=$(unzip -ql jdk-6u41-linux-i586.bin 2>&1 >/dev/null | sed -n -e 's/.\* ([0-9][0-9]
    tail -c $(expr $binsize - $zipstart) jdk-6u41-linux-i586.bin > tmp-jdk.zip  
expr: syntax error  
tail: jdk-6u41-linux-i586.bin: invalid number of bytes  
make: **\* [unpack-i586-stamp] Error 1  
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by flexiondotorg** [comment]
Just tested this on Lucid, Precise and Raring and all is working well.
