### ISSUE TITLE
Ubuntu 13.04 no longer has defoma

### ISSUE THREAD

**Issue by dhacker29** [flexiondotorg/oab-java6#92]
Removing it as a prerequisite allows script to properly package java for raring.

**Comment by SeeJayEmm** [comment]
https://bugs.launchpad.net/ubuntu/+source/defoma/+bug/1128669

**Comment by nawroth** [comment]
The oracle-java7-fonts package won't be correctly built without defoma.
I installed it manually from here:
https://launchpad.net/ubuntu/raring/amd64/defoma
And then the script built the package just fine.

What the package does:
"The Lucida fonts are included in the oracle-java7-jre package.
This package makes the fonts available to system."
