### ISSUE TITLE
fails to download jdk-6u43-linux-i586.bin

### ISSUE THREAD

**Issue by frko** [flexiondotorg/oab-java6#93]
Message : [x] Downloading jdk-6u43-linux-i586.bin :    http://: Invalid host name.
It seems to be the case indeed that the page downloaded contains no reference to a download location for EOL jdk-6u43-linux-i586.bin.

The actual download location can be found here : http://www.oracle.com/technetwork/java/javase/downloads/jdk6downloads-1902814.html.

**Comment by roberto-filho** [comment]
Been having the same problem, except with the 6u45 version. Had to hard code the URL for the 6u45 version into the script to make it work. :rocket:

**Comment by flexiondotorg** [comment]
Just tested 6u45 on Lucid, Precise and Raring and all is working correctly.
