### ISSUE TITLE
Debian 6 (64) script VER="0.2.7" ERROR! Packages failed to build.

### ISSUE THREAD

**Issue by webinteger** [flexiondotorg/oab-java6#94]
rm -rf jdk1.6.0_43
binsize=$(wc -c jdk-6u43-linux-i586.bin | awk '{print $1}'); \
<------>zipstart=$(unzip -ql jdk-6u43-linux-i586.bin 2>&1 >/dev/null | sed -n -e 's/.\* ([0-9][0-9]_) extra bytes._/\1/p'); \
<------>tail -c $(expr $binsize - $zipstart) jdk-6u43-linux-i586.bin > tmp-jdk.zip
expr: syntax error
tail: jdk-6u43-linux-i586.bin: invalid number of bytes
make: **\* [unpack-i586-stamp] Error 1
dpkg-buildpackage: error: debian/rules build gave error exit status 2 
^H^H4420's retcode: 2

**Comment by flexiondotorg** [comment]
I'm just preparing for the release of 0.2.8 and have successfully tested Debian Squeeze. All working correctly.
